let celsius = 6;
let fahrenheit;
fahrenheit = (celsius * 9) / 5 + 32;
console.log(fahrenheit);
let daysInMonth = 30;
let hoursInMonth = daysInMonth * 24;
console.log(hoursInMonth);
let minutesInMonth = hoursInMonth * 60;
console.log(minutesInMonth);
let playerHealth = 100;
let playerStamina = 100;
console.log(playerHealth - 70);
console.log(playerStamina - 59);
let totalPrice = 597;
let discount = 0.1;
let discountedPrice = totalPrice - totalPrice * discount;
console.log(discountedPrice);
const floatNumber = 12.78;
const roundedDown = Math.floor(floatNumber);
console.log(roundedDown);
const floatString = "45.67";
const parsedFloat = parseFloat(floatString);
console.log(parsedFloat);
const intString = "123";
const parsedInt = parseInt(intString);
console.log(parsedInt);
let number = 16;
let sqrtNumber = Math.sqrt(number);
console.log(sqrtNumber);
const integer = 42;
const stringNumber = "256";
const convertedInt = parseInt(stringNumber);
console.log(convertedInt);
const convertedString = integer.toString();
console.log(convertedString);
